### ISSUE TITLE
Cannot use tally when using preview to program in BlackMagic ATEM

### ISSUE THREAD

**Issue by kjetisve** [bitfocus/companion-module-birddog-studio#6]
Hi! Thanks for an awesome module.
I am using the stream deck with my three Bird Dog cameras, and I have three buttons for each camera that I use to send the camera to the Preview monitor on my BlackMagic ATEM. I have another button which takes whatever is in the preview monitor and sends it to the Program monitor.

The Bird Dog module only lets me set what is going to happen to a specific camera when I hit a button.
I would like to use my Preview to Program button to have a function that says

BIRD DOG CAMERA (X) > TALLY ON
and then set TALLY OFF if the Camera is taken off Preview.

I don't know if this was understandable, and if it is possible.
Just a suggestion!

Have a nice day!
Kind regards,
Kjetil

**Comment by bryce-seifert** [comment]
Hey there! One quick note that this module is for the Birddog Studio line of encoders / decoders. For the Birddog PTZ cameras, that is the [Birddog Visca module](https://github.com/bitfocus/companion-module-birddog-visca).

Regardless, I think I know how to make this work using the Triggers in the latest [2.2.0 betas](https://bitfocus.io/companion/download/builds/). You would need to set a button for each camera. One with Tally On, one with Tally Off. These don't need to be visible to you, just one a page somewhere.

Then, using triggers, you can make one for each camera using it's name in the ATEM. Basically, 

- You need a trigger for each camera to  press the button number for tally on when the` atem:prg_input` (this name will vary based on your set-up) is `=` to the label your camera has in the ATEM
- You need a trigger for each camera to  press the button number for tally off when the `atem:prg_input`  is `!=` to the label your camera has in the ATEM

Let me know if this makes sense or you have any questions setting it up. Going to close for now, since it's not directly related to this module but feel free to drop a line here or on Slack if you need more help.

<img width="316" alt="Screen Shot 2021-04-21 at 8 09 16 AM" src="https://user-images.githubusercontent.com/50299051/115558978-e368bf00-a278-11eb-81c8-6176dd87c93f.png">
<img width="790" alt="Screen Shot 2021-04-21 at 8 04 22 AM" src="https://user-images.githubusercontent.com/50299051/115558993-e6fc4600-a278-11eb-9c95-c71373cd840d.png">

**Comment by kjetisve** [comment]
> @kjetisve Were you able to get this working?

Hi! Yes, I was able to get it working - Thanks a lot! =)
